# Generated by Django 5.2 on 2025-07-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
