# Generated by Django 5.2 on 2025-05-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='email',
            field=models.EmailField(default='minthwayhtut568@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='phone_number',
            field=models.CharField(default='00000000', max_length=20),
            preserve_default=False,
        ),
    ]
