# Generated by Django 5.2 on 2025-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_car_email_car_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='email',
            field=models.EmailField(default='no email provided', max_length=254),
        ),
    ]
