# Generated by Django 5.2 on 2025-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_car_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
