# Generated by Django 5.2 on 2025-06-06 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_savedcar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.car'),
        ),
        migrations.AlterField(
            model_name='savedcar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
