# Generated by Django 5.2 on 2025-06-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_savedcar_car_alter_savedcar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('count', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='SavedCar',
        ),
    ]
